create table public.aluno (
  id_aluno integer generated by default as identity not null,
  nome_completo character varying(50) not null,
  data_nascimento date not null,
  sexo character varying(1) not null,
  cpf character varying(15) not null,
  telefone character varying(15) not null,
  escola_atual character varying(50) not null,
  serie_atual integer not null,
  periodo_escolar character varying(10) not null,
  nome_rua character varying(100) not null,
  numero_endereco integer not null,
  bairro character varying(50) not null,
  data_matricula date not null,
  observacoes text not null,
  cep character varying(20) null,
  ativo boolean not null default true,
  constraint aluno_pk primary key (id_aluno),
  constraint aluno_cpf_key unique (cpf)
) TABLESPACE pg_default;

create table public.matricula (
  id_matricula integer generated always as identity not null,
  aluno_id_aluno integer not null,
  turmas_id_turma integer not null,
  status character varying(20) not null,
  data_matricula date null default CURRENT_DATE,
  constraint matricula_pk primary key (id_matricula),
  constraint realiza foreign KEY (aluno_id_aluno) references aluno (id_aluno),
  constraint recebe foreign KEY (turmas_id_turma) references turma (id_turma)
) TABLESPACE pg_default;

create index IF not exists matricula_idx_1 on public.matricula using btree (aluno_id_aluno) TABLESPACE pg_default;

create index IF not exists matricula_idx_2 on public.matricula using btree (turmas_id_turma) TABLESPACE pg_default;

create trigger trg_atualiza_vagas_curso
after INSERT
or DELETE
or
update on matricula for EACH row
execute FUNCTION atualiza_vagas_curso ();

create table public.turma (
  id_turma integer generated always as identity not null,
  cursos_id_curso integer not null,
  dia_semana character varying(20) not null,
  vagas_turma integer not null,
  nome_turma character varying not null,
  descricao text null,
  hora_inicio time without time zone null,
  hora_fim time without time zone null,
  constraint turma_pk primary key (id_turma),
  constraint possui foreign KEY (cursos_id_curso) references curso (id_curso)
) TABLESPACE pg_default;

create index IF not exists turma_idx_1 on public.turma using btree (cursos_id_curso) TABLESPACE pg_default;

create table public.chamada (
  id_chamada integer generated by default as identity not null,
  users_id_usuario integer not null,
  turmas_id_turma integer not null,
  data_aula date not null,
  constraint chamada_pk primary key (id_chamada),
  constraint chamada_turmas foreign KEY (turmas_id_turma) references turma (id_turma),
  constraint chamada_users foreign KEY (users_id_usuario) references usuarios (id_usuario)
) TABLESPACE pg_default;

create index IF not exists chamada_idx_1 on public.chamada using btree (users_id_usuario) TABLESPACE pg_default;

create index IF not exists chamada_idx_2 on public.chamada using btree (turmas_id_turma) TABLESPACE pg_default;

create table public.presenca (
  id_presenca serial not null,
  chamada_id_chamada integer not null,
  aluno_id_aluno integer not null,
  presente boolean not null default false,
  observacao text null,
  constraint presenca_pkey primary key (id_presenca),
  constraint presenca_aluno_id_aluno_fkey foreign KEY (aluno_id_aluno) references aluno (id_aluno),
  constraint presenca_chamada_id_chamada_fkey foreign KEY (chamada_id_chamada) references chamada (id_chamada)
) TABLESPACE pg_default;