-- TABELA DE ALUNOS

create table public.aluno (
  id_aluno integer generated by default as identity not null,
  nome_completo character varying(50) not null,
  data_nascimento date not null,
  sexo character varying(1) not null,
  cpf character varying(15) not null,
  telefone character varying(15) not null,
  escola_atual character varying(50) not null,
  serie_atual integer not null,
  periodo_escolar character varying(10) not null,
  nome_rua character varying(100) not null,
  numero_endereco integer not null,
  bairro character varying(50) not null,
  data_matricula date not null,
  observacoes text not null,
  cep character varying(20) null,
  constraint aluno_pk primary key (id_aluno)
) TABLESPACE pg_default;

-- TABELA DE RESPONSÁVEIS

create table public.responsavel (
  id_responsavel integer generated always as identity not null,
  nome_completo character varying(50) not null,
  cpf character varying(15) not null,
  telefone character varying(15) not null,
  telefone_recado1 character varying(15) not null,
  telefone_recado2 character varying(15) not null,
  parentesco character varying(20) not null,
  constraint responsavel_pk primary key (id_responsavel)
) TABLESPACE pg_default;

-- TABELA DE RESPONSÁVEIS X ALUNOS

create table public.responsavel_aluno (
  responsavel_id_responsavel integer not null,
  aluno_id_aluno integer not null,
  tipo character varying(20) not null,
  constraint responsavel_aluno_pk primary key (responsavel_id_responsavel, aluno_id_aluno),
  constraint associado_a foreign KEY (responsavel_id_responsavel) references responsavel (id_responsavel),
  constraint vinculado_a foreign KEY (aluno_id_aluno) references aluno (id_aluno)
) TABLESPACE pg_default;

create index IF not exists responsavel_aluno_idx_1 on public.responsavel_aluno using btree (responsavel_id_responsavel) TABLESPACE pg_default;

create index IF not exists responsavel_aluno_idx_2 on public.responsavel_aluno using btree (aluno_id_aluno) TABLESPACE pg_default;

-- TABELA DE CURSOS

create table public.curso (
  id_curso integer generated always as identity not null,
  nome character varying(20) not null,
  vagas_totais integer not null,
  ativo boolean not null default true,
  vagas_restantes integer not null,
  constraint curso_pk primary key (id_curso)
) TABLESPACE pg_default;

-- TABELA DE TURMAS

create table public.turma (
  id_turma integer generated always as identity not null,
  cursos_id_curso integer not null,
  dia_semana character varying(20) not null,
  vagas_turma integer not null,
  nome_turma character varying not null,
  descricao text null,
  hora_inicio time without time zone null,
  hora_fim time without time zone null,
  constraint turma_pk primary key (id_turma),
  constraint possui foreign KEY (cursos_id_curso) references curso (id_curso)
) TABLESPACE pg_default;

create index IF not exists turma_idx_1 on public.turma using btree (cursos_id_curso) TABLESPACE pg_default;

-- TABELA DE MATRÍCULAS

create table public.matricula (
  id_matricula integer generated always as identity not null,
  aluno_id_aluno integer not null,
  turmas_id_turma integer not null,
  status character varying(20) not null,
  data_matricula date null default CURRENT_DATE,
  constraint matricula_pk primary key (id_matricula),
  constraint realiza foreign KEY (aluno_id_aluno) references aluno (id_aluno),
  constraint recebe foreign KEY (turmas_id_turma) references turma (id_turma)
) TABLESPACE pg_default;

create index IF not exists matricula_idx_1 on public.matricula using btree (aluno_id_aluno) TABLESPACE pg_default;

create index IF not exists matricula_idx_2 on public.matricula using btree (turmas_id_turma) TABLESPACE pg_default;

create trigger trg_atualiza_vagas_curso
after INSERT
or DELETE
or
update on matricula for EACH row
execute FUNCTION atualiza_vagas_curso ();
